# Generated by Django 5.2.7 on 2025-12-21 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="seat",
            name="reserved_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
